name: Deploy PHP App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_633396BD2F1C4E52B8FD94A6BA680D09 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_621EB65310AF4A7B8DBE8AE981AAE149 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BE3F676B40A44228A201698DB46B368 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: phpapp-quynh
          package: php-app
